title = "GlowLED的后花园"  # 这将显示为主页的大标题
languageCode = "zh-cn"
defaultContentLanguage = "zh-cn"

baseurl = 'https://glowled.github.io'
name = 'hugo-theme-reimu'
license = 'MIT'
licenselink = 'https://github.com/D-Sketon/hugo-theme-reimu/blob/main/LICENSE'
description = 'A Hakurei Reimu style Hugo theme'
homepage = 'https://github.com/D-Sketon/hugo-theme-reimu'
demosite = 'https://d-sketon.github.io/hugo-theme-reimu'

tags = ['Blog', 'Chinese', 'Responsive', 'Dark', 'Light']
features = ['Blog', 'Chinese', 'Responsive', 'Dark', 'Light']

[markup.highlight]
guessSyntax = true
noClasses = false

[author]
name = 'D-Sketon'
homepage = 'https://d-sketon.github.io/'

[markup.goldmark.extensions.passthrough]
enable = true
delimiters.block = [["\\[", "\\]"], ["$$", "$$"]]
delimiters.inline = [["\\(", "\\)"], ["$", "$"]]

